tube:
  image: abernix/meteord:node-8.11.3-base
  expose:
   - 8080
  volumes:
   - /home/dtube/src/output:/bundle
   - /var/run/docker.sock:/var/run/docker.sock:ro
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/tube
   - ROOT_URL=http://tube.steem.racing
   - VIRTUAL_HOST=tube.steem.racing
   - LETSENCRYPT_HOST=tube.steem.racing
   - LETSENCRYPT_EMAIL=anybucket@outlook.com

mongo:
  image: mongo:latest
