tube:
  image: abernix/meteord:binbuild
  ports:
   - "8080:80"
  volumes:
   - /home/steem/src/dtube/bundle:/bundle
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/tube
   - ROOT_URL=http://tube.steem.racing

mongo:
  image: mongo:latest
