tube:
  image: abernix/meteord:node-8.11.3-base
  ports:
   - "8080:80"
  volumes:
   - /home/dtube/src/output:/bundle
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/tube
   - ROOT_URL=http://tube.steem.racing

mongo:
  image: mongo:latest
